-- Create a table for bookings
-- 1. Create the Table (Registrations)
create table registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  userName text not null,
  userPhone text,
  courseName text,
  email text
);

-- 2. Enable Row Level Security (Safety ke liye)
alter table registrations enable row level security;

-- 3. Policy: Allow Public Insert (Taake Bot data daal sakay)
create policy "Allow public insert"
on registrations for insert
with check (true);

-- 4. Policy: Allow Public Read (Agar tumhe check karna ho)
create policy "Allow public read"
on registrations for select
using (true);